database:
  # the name of your JDBC driver
  driverClass: com.mysql.jdbc.Driver
  # the username
  user: root
  # the password
#  password:
  password: devd
  # the JDBC URL
#  url: jdbc:mysql://localhost:3306/pabt
  url: jdbc:mysql://ec2-52-41-17-220.us-west-2.compute.amazonaws.com/pabt
  # any properties specific to your JDBC driver:
  properties:
   charSet: UTF-8
   hibernate.show_sql: false
   hibernate.hbm2ddl.auto: validate
   hibernate.session.events.log: false
   hibernate.dialect: org.hibernate.dialect.MySQLDialect
  # the maximum amount of time to wait on an empty pool before throwing an exception
  maxWaitForConnection: 60s
  # the SQL query to run when validating a connection's liveness
  validationQuery: "/* MyApplication Health Check */ SELECT 1"
  # the minimum number of connections to keep open
  minSize: 8
  # the maximum number of connections to keep open
  maxSize: 256
  # whether or not idle connections should be validated
  checkConnectionWhileIdle: false
  checkConnectionOnBorrow: true
  maxConnectionAge : 10s

server:
  #adminMinThreads: 1
  #adminMaxThreads: 64
  applicationConnectors:
    - type: http
      port: 2700
      #- type: https
      # port: 8443
      # keyStorePath: example.keystore
      # keyStorePassword: example
      # validateCerts: false
  adminConnectors:
    - type: http
      port: 2701
      #- type: https
      # port: 8444
      # keyStorePath: example.keystore
      # keyStorePassword: example
      # validateCerts: false


logging:
  level: INFO
  appenders:
    - type: console
    - type: file
      threshold: ALL
      timeZone: IST
      logFormat: "%date %level [%thread] %logger{0} [%X{id}] %msg%n"
      currentLogFilename: /var/log/urlShortner/urlShortner.log
      archive: true
      archivedLogFilenamePattern: /var/log/urlShortner/urlShortner-%d{yyyy-MM-dd}.log
      archivedFileCount: 20

#http:
#  port: 2700